# ______            _            
# | ___ \          | |           
# | |_/ /___  _   _| |_ ___  ___ 
# |    // _ \| | | | __/ _ \/ __|
# | |\ \ (_) | |_| | ||  __/\__ \
# \_| \_\___/ \__,_|\__\___||___/
#
# By Minnymin3

UpdateChecker: true