#   _______  _______          _________ _______  _______   #
#  (  ____ )(  ___  )|\     /|\__   __/(  ____ \(  ____ \  #
#  | (    )|| (   ) || )   ( |   ) (   | (    \/| (    \/  #
#  | (____)|| |   | || |   | |   | |   | (__    | (_____   #
#  |     __)| |   | || |   | |   | |   |  __)   (_____  )  #
#  | (\ (   | |   | || |   | |   | |   | (            ) |  #
#  | ) \ \__| (___) || (___) |   | |   | (____/\/\____) |  #
#  |/   \__/(_______)(_______)   )_(   (_______/\_______)  #
#
# By Minnymin3

#Enable of disable the UpdateChecker.
UpdateChecker: true

#Enable of disable the autoroute functionality.
Enable-Auto-Route: true

#AutoRoute default destination radius.
Auto-Route-Radius: 10

#Default timer time between '/routes next' attempts (seconds)
Enable-Command-Delay: true
Command-Delay: 60

#Messages to send to the player. 
#See 'Colour codes' on the forum page for more information on colours.
#POINT can be used in the description and name messages to show the point of that description/name.
Messages: 
   Need-Permission: Insufficient permission.
   Need-Permission-Colour: 4

   Default-Description: Route number POINT
   Default-Description-Colour: 7
   
   Default-Name: Route number POINT
   Default-Name-Colour: 7
   
   Delay: You must wait to use that function.
   Delay-Colour: 7

   Route-End: And so ends your quest...
   Route-End-Colour: 7

   Route-Next: Pointing to the next location...
   Route-Next-Colour: 7

   Route-Back: Pointing to the previous location...
   Route-Back-Colour: 7
   
   AutoRoute:
   
      Start: And your quest begins...
      Start-Colour: 7

      End: And so ends your quest...
      End-Colour: 7

      Default-Arrive: You have reached point POINT
      Default-Arrive-Colour: 7